### ISSUE TITLE
Unable to get app as expected in Exercise-2 Task-3

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Leveraging-Azure-Digital-Twins-in-a-supply-chain#6] opened 2021-11-18 07:14 UTC
In [Exercise-2 Task-3 Step-2](https://github.com/microsoft/MCW-Leveraging-Azure-Digital-Twins-in-a-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md), **Getting Started -> Running digital-twins-explorer locally** after following the steps unable to see the browser opened with the app.

Getting an error that: **'ERR_PACKAGE_PATH_NOT_EXPORTED'**. Please find the below screenshot for your reference.

![image](https://user-images.githubusercontent.com/83394010/142368255-2fc4722a-0fd0-409c-9e5b-fb96adbba707.png)

**Comment by codingbandit** [comment] 2021-11-18 15:59
Hi @Karthikkc123 - I noticed you've already created an issue in the Azure Digital Twins Explorer repository. This is the appropriate place as this lab does not maintain the code-base for that application.

**Comment by timahenning** [comment] 2021-12-08 17:17
Closing the issue.  We could not reproduce the error pertaining to this lab.

**Closed by timahenning** 2021-12-08 17:17 UTC
